name: build

on: [push, pull_request]

env:
  SLN:  CsvLINQPadDriver.sln
  SLN5: CsvLINQPadDriver5.sln
  SLN_CONFIG: Release
  BIN_POSTFIX: .Bin
  RETENTION_DAYS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # LINQPad 7/6

    - name: Setup .NET Core 6.0 SDK
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x'

    - name: Setup .NET Core 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0.x'

    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '3.1.x'

    - name: ${{env.SLN}} ${{ env.SLN_CONFIG }} clean
      run: dotnet clean ${{ env.SLN }} --configuration ${{ env.SLN_CONFIG }} && dotnet nuget locals all --clear

    - name: ${{env.SLN}} restore dependencies
      run: dotnet restore ${{ env.SLN }}

    - name: ${{env.SLN}} ${{ env.SLN_CONFIG }} build
      run: dotnet build ${{ env.SLN }} --configuration ${{ env.SLN_CONFIG }} --no-restore

    - name: ${{env.SLN}} ${{ env.SLN_CONFIG }} test
      run: dotnet test ${{ env.SLN }} --configuration ${{ env.SLN_CONFIG }} --no-build --verbosity normal

    # LINQPad 5

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: ${{env.SLN5}} restore dependencies
      run: nuget restore ${{ env.SLN5 }}

    - name: ${{env.SLN5}} ${{ env.SLN_CONFIG }} build
      run: msbuild ${{ env.SLN5 }} /p:Configuration=${{ env.SLN_CONFIG }}

    # Create LPX

    - name: Build LPX
      run: Deploy/buildlpx.cmd

    # Upload artifacts

    - name: Publish CsvLINQPadDriver
      uses: actions/upload-artifact@v2
      with:
        name: CsvLINQPadDriver${{ env.BIN_POSTFIX }}
        path: |
          bin/${{ env.SLN_CONFIG }}/CsvLINQPadDriver.*.nupkg
          Deploy/*.lpx
          Deploy/*.lpx?
        retention-days: ${{ env.RETENTION_DAYS }}

    - name: Publish LPRun
      uses: actions/upload-artifact@v2
      with:
        name: LPRun${{ env.BIN_POSTFIX }}
        path: bin/${{ env.SLN_CONFIG }}/LPRun.*.nupkg
        retention-days: ${{ env.RETENTION_DAYS }}
